apostrophecms/sanitize-html

index.js, package.json, test/test.js
Basic implementation of #4 that is sufficient for my use cases.  If you have any concerns or suggestions, let me know.
Basically what happens is that if an allowedAttribute has a `'*'` in it, that is replaced by `'.*'` and a single regular expression is built to test allowed glob attributes.
Example:
For `allowedAttributes: ['data-*', '*-foo']`, `allowedAttributesGlobMap[tag]` would be `/^(data-.*|.*-foo)$/`.
=> Allow globbed allowedAttributes

index.js, test/test.js
This change allows scheme rules on a per-tag basis, in case you
want to limit the schemes that a certain tag can have, while not
enforcing the same restriction on another.
Closes #50
=> [feat] Add per-tag scheme rules

index.js, package.json
**Tests pass**
- Removed `lodash` dependency.
- Added [`array-includes`](https://npmjs.com/package/array-includes) dependency. ([`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) polyfill.)
- Added [`xtend`](https://npmjs.com/package/xtend) dependency. (Replaces `_.defaults`)
I also shortened a few verbose statements:
```js
// was
var whateverMap;
allowedTagsMap = {};
_.each(options.whatever, function(tag) {
whateverMap[tag] = true;
});
// ... later ...
if (whateverMap && !_.has(whateverMap, name)) {
```
```js
// is now
if (options.whatever && !options.whatever.includes(name)) {
```
=> Removed lodash dependency

index.js, package.json
Using `array.indexOf` instead of `array.includes`.
- Removed `array.includes` shim.
- Modified instances of `array.includes(whatever)` => `array.indexOf(whatever) !== -1`
- Added a few forgotten semicolons.
- Split a long line
=> using array.indexOf instead of array.includes

index.js, package.json
Tests pass this time.
The issue in #65 was this expression...
```js
if (!array.indexOf(whatever) !== -1)
```
...is written wrong. First, it "nots" the `array.indexOf` expression, then it compares. I didn't think about that when converting from `array.includes`.
```js
var array = [0, 1, 2]
console.log(array.indexOf(0) !== -1) // => true
console.log(!array.indexOf(0) !== -1) // => true (this is what was happening)
console.log(!(array.indexOf(0) !== -1)) // => false
console.log(array.indexOf(0) === -1) // => false
```
=> array.indexOf instead of array.includes

index.js, test/test.js
The use case for this is if you want to validate a certain attribute on every element. For example, my usecase: running a CSS sanitize on every element's style attribute.
=> Added the ability to transform every element using '*'

README.md, index.js, test/test.js
Simple addition that allows the user to pass in options to the htmlparser2
=> Allow setting of htmlparser2 options

README.md, index.js, test/test.js
When I used sanitizer with whitelist option, I run into situation, when i wanted to allow a LOT of tags, and a LOT of attributes. But it was a pain to describe attributes for each of tags. So i made small changes, to allow some attributes to be allowed on any tag, declaring them like:
```javascript
allowedAttributes: {
'*': [ 'href', 'align', 'alt', 'center', 'bgcolor' ]
}
```
It works, and it's handy for me. I am reconsidering to make some default whitelists too, because default whitelist is a way too restricted for HTML editors, for example.
=> Feature: adding option to allow list of attributes to any tag.

README.md
I was initially confused, thinking that setting:
allowedTags: false,
allowedAttributes: false
would disallow all tags.  The correct answer is to set them to empty arrays.
Updated the docs to reflect this and added some additional formatting to the questions to make them easier to scan.
=> Add info about disallowing tags, add formatting

test/test.js
Hello!
We found a regression with the last update, I could replicate it with this test, but I'm not able to fix it in the code.
Can you please have a look?
Thanks!
```
57 passing (78ms)
1 failing
1) sanitizeHtml should drop the content of textarea elements but keep the closing parent tag, when nested:
AssertionError: '<p>Paragraph' == '<p>Paragraph</p>'
+ expected - actual
-<p>Paragraph
+<p>Paragraph</p>
at Context.<anonymous> (test/test.js:50:12)
```
=> Regression on last update when nesting tags

.gitignore, README.md, package.json
discussion: #112 (https://github.com/punkave/sanitize-html/issues/112)
Build commands for creating packaged sanitize-html JS files for use in the front end.
`npm run build`: runs unit tests and creates an unminified browserify-ied sanitize-html.js
`npm run minify`: runs unit tests, build, and uses uglify to minify the sanitize-html.js file as sanitize-html.min.js
`npm run prebuild`: execute unit tests and create a fresh dist directory
For npm commands, can we run mkdir on a Windows box? Does npm abstract this away? Or are they just shell commands?
=> Npm run build / npm run minify

README.md, index.js, test/test.js
This adds support for adding new text (innerText) to an element that has no text initially set.
For example, this element:
<a href="http://somelink.com"></a>
Can now be transformed  to:
<a href="http://somelink.com">some text</a>
Amazing module btw, I'm finding this indispensable for retooling existing pages to AMP markup.  With this PR, I can do something like this as a fallback for unsupported/illegal elements:
<iframe src="http://somelink.com"></iframe>
Transforms to:
<a href="http://somelink.com">some text</a>
=> Support adding new text to an element that has no initial text.

index.js
Set to true by default, this can be set to false to avoid //evil.com/nasty or evil.com/nasty being allowed as hrefs.
=> Add option to allow empty URL schemes

README.md, index.js, package-lock.json, package.json, test/test.js
This is an updated pull request from @cwill747 [original](https://github.com/punkave/sanitize-html/pull/98)
The `allowedStyles` option now requires a list of regular expressions for whitelisting. This makes whitelisting attributes such as font-size: 30px much easier because all unit types don't have to be accounted for within our logic.
=> CSS Sanitization

README.md, index.js, package.json, test/test.js
Adds the ability to parse _inline_ css and decide whether or not to include it based off of the tag names. Uses the css library to parse out the inline css, filters it, then stringify's the CSS and re-inserts it, meaning that some whitespace or semicolons could be lost on the reparsing.
Definitely needs some code review.
=> Allow for filtering of CSS Styles

index.js, package-lock.json, package.json
Fixes the deprecation issue.
```
sanitize-html > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
```
=> replace lodash.isarray with Array.isArray

README.md, package.json, src/index.js, test/test.js
Hey @boutell looks like I'm the motivated developer 😄 . 
This PR makes it so the user can pass allowable urls as a property to the sanitizeHtml function which will strip out any urls from an iframe tag's src attribute that are not included in the allowable urls property array. 
This is accomplished by just adding a new property to the options object passed to the function like so: 
```
clean = sanitizeHtml(dirty, {
allowedTags: ['p', 'iframe', 'a', 'img', 'i'],
    allowedAttributes: {
        'iframe': ['src', 'href'],
        'a': ['src', 'href'],
        'img': ['src']
    },
    allowedUrls: ['youtube.com', 'vimeo.com']
})
```
The PR contains some default urls allowed (youtube.com and vimeo.com), I'm happy adjust these or remove them as you see fit. I can simply add a conditional for …
=> Allow filtering of iframe src urls

README.md, src/index.js, test/test.js
New test for 'allowedSchemes not being applied to cite'  #200
```javascript
assert.equal(sanitizeHtml('<q cite=\"http://www.google.com\">HTTP</q><q cite=\"https://www.google.com\">HTTPS</q><q cite=\"mailto://www.google.com\">MAILTO</q><q cite=\"tel://www.google.com\">TEL</q><q cite=\"ftp://www.google.com\">FTP</q><q cite=\"data://www.google.com\">DATA</q><q cite=\"ldap://www.google.com\">LDAP</q><q cite=\"acrobat://www.google.com\">ACROBAT</q><q cite=\"vbscript://www.google.com\">VBSCRIPT</q><q cite=\"file://www.google.com\">FILE</q><q cite=\"rlogin://www.google.com\">RLOGIN</q><q cite=\"webcal://www.google.com\">WEBCAL</q><q cite=\"javascript://www.google.com\">JAVASCRIPT</q><q cite=\"mms://www.google.com\">MMS</q>',{
allowedTags: sanitizeHtml.defaults.allowedTags.concat( ['q', 'cite'] …
```
=> New test for allowedSchemes for cite

README.md
Remove stray $ from the example filter for `font-size`.  Use grouping rather than charset for alternatives.
Note might opt to use capture rather than non-capture grouping to make consistent with other examples.
=> Fix regex in font-size filtering example in README.md

README.md
This fixes misleading misprint in the README that shows that the iframe `src` should be added to `allowedAttributes`. 
In re: #215
=> Updated iframe whitelist misprint

package.json
Avoid packers to use the node version that doesn't transpile es6 code (like ansi-styles one for example).
This currently force all browser user to transpile the code with babel or something else.
With this browser declaration, the transiled version is directly used.
=> Add browser support declaration for packers detection like webpack.

package.json
The 'browser' field should be a node module intended for use in
a web browser, eg. using the `window` object or similar as per
https://docs.npmjs.com/files/package.json#browser . It's what
webpack imports if the key exists. This points it to browserified
source code which isn't what webpack wants.
Also the sanitize-html.js published to npm seems to be an empty
module, I don't know why this is yet, but either way I don't
believe this key should be here. It description says it was to make
packers use the transpiled version rather than the ES6 version,
but it was already pointing at `dist/index.js` which is the babel
transpiled version.
Fixes https://github.com/punkave/sanitize-html/issues/241
=> Revert https://github.com/punkave/sanitize-html/pull/226

package.json, src/index.js
`postcss` is a pretty heavy weight dependency if it is only being used for parsing an AST.
Replaced with [css-tree](https://www.npmjs.com/package/css-tree).
=> Remove dependency on postcss

src/index.js
Hi,
I was trying to validate html on server side with sanitize-html and realized that the plugin was adding a semi-colon on closing style="".
The input was generated by CKEditor4 and looked like this `<div style="width:200px"></div>`
(notice the missing closing semi-colon) which is actually fine according to CSS2 specs that says that semi colon are used to separate, not terminate.
=> Remove semicolon to close style=""

README.md, src/index.js, test/test.js
Added the option to escape disallowed tags instead of stripping or discarding them. 
Escaping is a rather common use-case (a user naively sending `<span>hello</span>` would expect it to render like that, and not stripped down to `hello`), which is also referenced in #57 .
=> Escape disallowed tags

test/test.js
`npm test` is currently broken, this PR fixes it.
The problem was `require`-ing the wrong filename in `test.js` (`index.js` instead of `sanitize-html.js`).
=> Fixed require statement in test.js

package.json
Seems mostly meta release and drops one dependency: https://github.com/sindresorhus/srcset/releases
Tested that `npm test` passes.
=> Update srcset dependency from v1 to v2

package.json
✅Tested that `npm test` passes.
Performance improvement: https://github.com/chalk/chalk/releases/tag/v3.0.0
...but wait, chalk isn't referenced or used anywhere in `sanitize-html`? There's an old backstory at https://github.com/apostrophecms/sanitize-html/issues/195
...different thing is this is relevant anymore. 🤷‍♂️
=> Update chalk from v2 to v3

README.md, src/index.js, test/test.js
Based on #108 . Closes #313 
This will allow devs to check for media elements so elements can be maintained even if there is no text inside them. Previous discussions have revolved around self-closing tags (or "[void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements)", T.I.L.), but not all self-closing tags meet the use cases described (e.g., `hr`, `br`). By specifically checking for media elements, we can meet the use cases described -- primarily link anchor tags with images inside being collapsed.
=> Adds mediaChildren property to frames for filtering

CHANGELOG.md, package.json, src/index.js
Lodash is quite big project with a lot of code which can be useless for
end user. https://packagephobia.com/result?p=lodash
I suggest to migrate to small popular packages without dependencies.
- `lodash/escapeRegExp` -> `escape-string-regexp` (node v10 is required)
- `lodash/cloneDeep` -> `klona`
- `lodash/mergeWith` -> `deepmerge` (immutable and arrays are concatenated by default)
- `lodash/isString` -> `typeof value === 'string`
- `lodash/isPlainObject` -> `is-plain-object` (no dependencies in latest version)
=> Replace lodash with small packages

package.json
Ref https://github.com/jonschlinkert/is-plain-object/releases/tag/v4.0.0
The new version behaves closer to lodash/isPlainObject by considering
`Object.create(null)` as plain object.
=> Upgrade is-plain-object

package.json, src/index.js, test/test.js
Replace [srcset](https://github.com/sindresorhus/srcset) with [parse-srcset](https://github.com/albell/parse-srcset) to address https://github.com/apostrophecms/sanitize-html/issues/367.
Additionally, fix tests with invalid srcset containing both width descriptor and pixel density descriptor. [Only zero or one of those is allowed](https://html.spec.whatwg.org/multipage/images.html#srcset-attributes).
=> Fix srcset parsing

CHANGELOG.md, index.js, package.json, test/test.js
Ref https://github.com/lukeed/klona/releases/tag/v2.0.0
The new version got a few new modes and migrated to named export.
=> [v2] Upgrade klona

README.md
In v2, `defaults.allowedTags` has been updated. Unfortunately the README.md contains an out-of-date version of the `allowedTags` config variable.
This PR updates the README.md with the current `defaults.allowedTags` value.
=> Update default allowedTags in README.md

CHANGELOG.md, README.md, index.js
It seems subscript (`<sub>`) is allowed, but `<sup>` is not, so this commit adds `sup` to the list of default allowedTags
=> Allow superscript tag by default

CHANGELOG.md, index.js, package.json, test/test.js
The WHATWG URL parser doesn't agree with browsers about these, so a regexp of our own is needed. Fortunately however they rely on behaviors regarding the protocol part of the URL which is the easiest part to clean before passing to WHATWG. Tests contributed by our friends at Checkmarx.
=> new and interesting iframe validation exploits

README.md
Super minor fix to the README to set the language on the JS imports for better rendering.
Before:
After:
=> docs: tweak code language in README for JS imports

CHANGELOG.md, README.md, index.js, package.json, test/test.js
Support wildcards in `allowedClasses` like this:
```javascript
allowedClasses: {
p: ["prefix-*"]
}
```
---
Useful especially for allowing the `language-xxx` syntax indicator classes in [highlight.js](https://highlightjs.org/).
Attempts have been made in #157, and here I tried to build up a glob map before the loop for better performance, the same as what was done for allowed Attributes. And the wildcard may match zero character for consistency with allowed Attributes too.
All tests passed.
=> Support wildcards in allowedClasses (update to #157)

CHANGELOG.md, README.md, index.js, test/test.js
I needed the same feature stated here: https://github.com/apostrophecms/sanitize-html/issues/405
Added allowedScriptHostnames and allowedScriptDomains
=> Allow script tags for specific domains / hostnames

CHANGELOG.md, index.js, package.json, test/test.js
Limiting the src attribute has no meaning if you can put the same malicious code right in the body, so this is a security fix, not a bc break.
Closes #494
=> PRO-2076 no script tag bodies allowed at all when locking down to certain script sources

CHANGELOG.md, index.js, test/test.js
Note that nullish values also include 0, but according to [this comment](https://github.com/apostrophecms/sanitize-html/pull/102#issuecomment-872242667) of a repo member: 
> In any case it is up to the caller to pass a string.
=> Fix #486: Return an empty string when input is a nullish HTML

README.md, index.js, test/test.js
Using wildcard on allowedClasses poses a security risk. Having regex support on classes is a better solution where you can be more explicit with the whitelisting.
Disclaimer: This is a performant way of allowing Regular Expressions on the existing codebase in a couple of lines :)
=> allowedClasses support for regex expressions

CHANGELOG.md, index.js, test/test.js
Fixes issue #506
Fixes regression caused by https://github.com/apostrophecms/sanitize-html/pull/395 in which `addedText` was never reseted to false after the `ontext` function was called for that tag.
Solution: reset `addedText` boolean to false in the onclosetag function.
=> Fix trailing text issue on transformTag 

CHANGELOG.md, README.md, index.js
Allow common image attributes by default. If the `src` attribute is going to be enabled without images being enabled, it makes sense to also allow other commonly used tags to reduce confusion when using the library.
The `alt` attribute is also required on `<img />` tags by the HTML standard so it shouldn't be removed by default.
Closes #525
=> Add common image attributes

CHANGELOG.md, index.js, test/test.js
Allow relative url in script tags. Logic is the same like in iframe tag. 
* Closes  #531 - 
Proper test has been written to cover this situation. Test name: 
> Should allow protocol-relative URLs for script tag
=> Fix protocol relative url in scripts tags #531

CHANGELOG.md, index.js, test/test.js
Closes #549 
The snippets given in the issues should now work as expected.
=> Another case of bad markup identified in Issue#549. Closing tags without having opening tags. Test cases also added.

CHANGELOG.md, index.js, test/test.js
Closes #176 
Run the following example snippet.
```
sanitizeHtml('<div><wiggly worms="ewww">hello</wiggly></div>', {
allowedTags: undefined
})
```
Before this change, we used to get the following output, ie. all tags allowed:
`'<div><wiggly worms="ewww">hello</wiggly></div>'`
After this change, we will get the following output, ie. no tag allowed:
`'hello'`
I have added new test cases to check the behaviour needed.
=> For allowedTags, stop treating falsy values other than false, same as false.

CHANGELOG.md, README.md, index.js, test/test.js
This will fix https://github.com/apostrophecms/sanitize-html/issues/547
This PR introduces a new option:
```
options.parseStyleAttributes: boolean
```
By default set to true, to match the current behavior. But a user can set it to false, to skip parsing style tags.
This can avoid issues when the package is used in the browser.
```javascript
it('Should ignore styles when options.parseStyleAttributes is false', function() {
assert.equal(
sanitizeHtml('<span style=\'color: blue; text-align: justify\'></span>', {
allowedTags: false,
allowedAttributes: {
span: [ 'style' ]
},
allowedStyles: {
span: {
color: [ /blue/ ],
'text-align': [ /left/ ]
}
},
parseStyleAttributes: false
}), '<span style="color: blue; text-align: justify"></span>'
);
});
```
=> feat(parseStyleAttributes): add option to skip style parsing [fix 547]

CHANGELOG.md, package.json
There was already a 2.8.1 release, probably the new publish attempt failed and I missed it because I was doing too many things at once.
No new functionality here, just releasing what we had already said was released in response to a ticket.
=> oops, we forgot to release parseStyleAttributes

CHANGELOG.md, index.js, test/test.js
Closes #464 
Adds `tagAllowed()` helper function.
Existing tests may need to be reviewed. I don't do a lot of PRs, sorry.
=> Fix auto-adding escaped closing tags

CHANGELOG.md, index.js
See issue #613
> 1. Execute ```require(".")("<div style='invalid style'></div>", { allowedAttributes: { div: [ 'style' ] } })``` in node
> 2. Make sure no warnings are displayed. 
> 3. Execute same code in browser
> 4. Check if warning is displayed.
=> Show parseStyleAttributes warning in browser only

CHANGELOG.md, README.md, index.js, test/test.js
This causes sanitize-html to remove empty attributes that are known to be non-boolean. It provides an exhaustive list of all known attributes taken from: https://html.spec.whatwg.org/multipage/indices.html#attributes-3
* User controlled via `options.nonBooleanAttributes`
* Enabled by default, and can be disabled by passing in `nonBooleanAttributes: []`
* Can handle all empty attributes via `nonBooleanAttributes: ['*']`
Closes #123 
Test with empty attributes such as:
```
<input checked type="checkbox" />
```
Will not remove anything.
```
<input checked form type="checkbox" />
```
Will transform into the first example.
=> feat: remove empty non-boolean attributes

CHANGELOG.md, README.md, index.js, test/test.js
Prior to 2.4.0, `allowedClasses` can be false, this has been an undocumented feature.
Since 2.4.0, this behavior is broken. This PR reverted to the previous behavior where `false` is allowed in the `allowedClasses` attribute.
See https://github.com/apostrophecms/sanitize-html/discussions/621 for more detail
The following code is broken in the main branch of this base repo, but should work in the branch in this pr.
```javascript
const sanitizeHtml = require('sanitize-html');
const ALLOWED_TAGS = [
'li',
'ul',
'ol',
'p',
'h1',
'h2',
'h3',
'h4',
'h5',
'h6',
'img',
'a',
'div',
'b',
'table',
'tbody',
'tr',
'th',
'td'
];
const ALLOWED_SCHEMES = ['https', 'mailto'];
const sanitized = sanitizeHtml(`<ul class="should not sanitize"><li>Hello </li></ul>`, {
allowedAttributes: { '*': ['*'] }, …
```
=> Bug Fix: allow false in allowedClasses

CHANGELOG.md, index.js, test/test.js
Issue: #633 
Closes #633 
* Added allowedEmptyAttributes option with default attribute 'alt'
* Added check to keep empty attributes that specified in allowedEmptyAttributes option
* Added unit tests
run unit test - `npm run test`
*For example:*
If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for …
=> Added 'allowedEmptyAttributes' option and kept empty 'alt' value by default

CHANGELOG.md, README.md, test/test.js
In this PR I have added a test case for the SVG element to prevent the element from lowercased and same for the attributes.
=> allow svg element

CHANGELOG.md, index.js, test/test.js
Do not process source maps when using PostCSS.
Test provided in PR.
=> fix: ignore source maps when processing with postcss

CHANGELOG.md, index.js, test/test.js
`transformTags` can now set the text content of discarded tags, even if it originally had no text child elements.
Closes https://github.com/apostrophecms/sanitize-html/issues/682
Also added a test case after reading the [bonus line in contributing.md :P](https://github.com/apostrophecms/.github/blob/main/CONTRIBUTING.md#reporting-bugs)
See https://github.com/apostrophecms/sanitize-html/issues/682 / newly added test
Not sure if it needs a change in documentation.
=> Bugfix: Setting text with transformTags in cases where the element originally had no text content 

index.js
In the default list, there was a duplicate "main" element and "menu" was missing. It seems like the list was taken from "https://developer.mozilla.org/en-US/docs/Web/HTML/Element#text_content". There, "menu" is in the exact same spot where the duplicate "main" was, so I guess it was a typo :-)
*For example:*
- [] Related documentation has been updated
If adding a new …
=> fix: remove duplicate "main" from default and use "menu" instead

CHANGELOG.md, README.md, index.js, test/test.js
Allows hooking into tag tag open, tag close, and text events of the parser to enable more advanced transformations such as inserting a space between two removed block-level tags with preserved text.
Closes #691.
Added a simple test in the test suite, but you can also test manually by passing the `onOpenTag`, `onCloseTag`, and `onText` listeners in the sanitizer options.
=> feat: add tag open, tag close, and text events

README.md, index.js, test/test.js
Fixes https://github.com/apostrophecms/sanitize-html/issues/540
Add `preserveEscapedAttributes` option to allow attributes on escaped disallowed tags to be retained. Closes #540 
You can try the new behaviour by setting `preserveEscapedAttributes` to `true` when `disallowedTagsMode` is `'escape'` or `'recursiveEscape'`.
Added unit tests to PR. 
=> Add `preserveEscapedAttributes` option to retain all attributes of escaped disallowed tags
