- README.md
- index.js
- test/test.js
Please note that custom processing is done once text is already HTML escaped.
> Allow custom processing for text nodes

- index.js
- package.json
Reverts punkave/sanitize-html#65
> Revert "using array.indexOf instead of array.includes"

- README.md
I noticed that the default options in the Readme were out of date. I updated them with the latest from the source code.
> Update Readme to latest default options

- package.json
Running ```npm install``` followed by ```npm test``` failed. Added mocha to the dev dependencies.
> ran npm install mocha --save-dev to make npm install mocha automatically

- .gitignore
- README.md
- package.json
Reverts punkave/sanitize-html#113
> Revert "Npm run build / npm run minify"

- .gitignore
- README.md
- package.json
Reverts punkave/sanitize-html#114
> Revert "Revert "Npm run build / npm run minify""

- index.js
- test/test.js
> Disallow URLs starting with /\ in case allowProtocolRelative is false

- package-lock.json
- package.json
Following this discussion: https://github.com/punkave/sanitize-html/issues/195#issuecomment-355746502
> add chalk to dependencies

- README.md
- package.json
- src/index.js
- test/test.js
> Add test for specific attribute values

- README.md
Hi there, this was caught by our tests and caused a little bit of confusion. Apologies for the formatting noise.
> Update list of allowed tags in README.md

- README.md
- package.json
- src/index.js
- test/test.js
Addresses https://github.com/punkave/sanitize-html/issues/249
> Stop double encoding ampersands on HTML entities

- README.md
Updated default options in README.md to match sanitizeHtml.defaults in index.js
> Update default options in README.md

- README.md
- src/index.js
- test/test.js
Reverts apostrophecms/sanitize-html#169
> Revert "Escape disallowed tags"

- README.md
- src/index.js
- test/test.js
A reopening of #169 after fixing build and tests and rebasing onto fresh master.
> Escape disallowed tags

- src/index.js
> fix "Cannot read property length of undefined"

- README.md
- src/index.js
- test/test.js
https://github.com/apostrophecms/sanitize-html/compare/master...slavaGanzin:textFilterTagNameAttribute?expand=1#diff-c1129c8b045390789fa8ff62f2c6b4a9R486
> textFilter(text) -> textFilter(text, tagName)

- .eslintignore
- .eslintrc
- CHANGELOG.md
- package.json
- src/index.js
- test/test.js
See comments below for changes that aren't simply white space.
> Adds eslint and bumps version

- README.md
- src/index.js
> feat: add abbr to default list

- src/index.js
- test/test.js
Test and fix for https://github.com/apostrophecms/sanitize-html/issues/353
Closes #353
> Fix escaping of self closing tags

- CHANGELOG.md
- README.md
- package.json
- src/index.js
- test/test.js
> Adds option to the nonTextTagsArray array

- .gitignore
- README.md
- src/index.js
- test/test.js
> Introduce allowedIframeDomains

- CHANGELOG.md
- package.json
I didn't find this dependency is used anywhere.
> Drop chalk

- CHANGELOG.md
- package.json
- src/index.js
Ref https://github.com/apostrophecms/sanitize-html/issues/257
> Replace xtend with builtin Object.assign

- CHANGELOG.md
- index.js
- package.json
- test/test.js
Ref https://github.com/sindresorhus/srcset/releases/tag/v3.0.0
The new version matches latest spec and requires node v10.
> Upgrade srcset

- README.md
Updates the README to remove build references
> Basic README updates re: no build

- CHANGELOG.md
- package.json
- src/index.js
- test/test.js
> Parse srcset

- CHANGELOG.md
- package.json
This appears to be the only file necessary at runtime
> Add `files` to package.json for v2

- CHANGELOG.md
- package.json
- src/index.js
- test/test.js
> Fixes issue with using transformTags without textFilter

- CHANGELOG.md
- package.json
- src/index.js
> Replaces includes with _.indexOf

- src/index.js
> Replaces another usage of includes

- CHANGELOG.md
- package.json
Updates the changelog and proposes making this a release candidate. Given we didn't change much at all in the v2 so far, this feels stable enough to start thinking about production releasing.
> 2.0.0 rc.1

- CHANGELOG.md
- index.js
- package.json
Ref https://github.com/jonschlinkert/is-plain-object/releases/tag/v5.0.0
> Upgrade is-plain-object

- README.md
This ports an update in the 1.x readme to 2.x
> Updates README import language

- CHANGELOG.md
- README.md
- index.js
- package.json
- test/test.js
There is also an eslint formatting update here, but it should be easier to read with github's "ignore whitespace changes" feature.
> nestingLimit option

- CHANGELOG.md
- index.js
- package.json
See changes here https://github.com/postcss/postcss/releases/tag/8.0.0
> Upgrade postcss

- README.md
- index.js
- test/test.js
> Wildcard support for allowedClasses

- README.md
- format all mentions of sanitize-html in the same way
- fix a link
- add a few commas for readability
- fix the case of some characters
- remove space before colons
- align a response to a FAQ
> Fix small things in README

- CHANGELOG.md
- README.md
- package.json
This comes up a fair bit and I thought it'd be worth directing people before they might create an issue.
> Adds note to the README about typescript

- CHANGELOG.md
- README.md
- index.js
> Allow 'tel' links by default

- CHANGELOG.md
- package.json
The `tel` change deserves a minor version bump, imo.
> bumps the version number

- CHANGELOG.md
- index.js
- package.json
- test/test.js
Ref https://github.com/fb55/htmlparser2/releases/tag/v5.0.0
> Upgrade htmlparser2

- README.md
This Node version was specified in an issue, #376, but not included in the README.
> Updates README to specify node version

- CHANGELOG.md
- README.md
- index.js
- package.json
- test/test.js
Following up from discussion in #480. No code changes.
> Replaces uses of whitelist

- index.js
> Fix #504: fix inconsistent iframe src behavior across browsers

- index.js
Reverts apostrophecms/sanitize-html#505
> Revert "Fix #504: fix inconsistent iframe src behavior across browsers"

- CHANGELOG.md
- index.js
- test/test.js
> Fixes important stripping

- CHANGELOG.md
> zade credit

- CHANGELOG.md
- package.json
Release 2.7.0
Release. package.json and changelog
> release 2.7.0

- CHANGELOG.md
- package.json
> bump version to 2.7.2

- CHANGELOG.md
- package.json
> release 2.8.0

- CHANGELOG.md
- index.js
- test/test.js
Fixes https://github.com/apostrophecms/sanitize-html/issues/593
*For example:*
> 1. npm install
> 2. npm run test
- [-] Related documentation has been updated
> Fix behavour for numbers

- CHANGELOG.md
- package.json
> release 2.8.1

- CHANGELOG.md
Adds thank you for community contribution.
*For example:*
> add thank you

- CHANGELOG.md
- package.json
> release 2.11.0

- CHANGELOG.md
- package.json
For release only.
*For example:*
> release 2.12.0

- CHANGELOG.md
Adds thank you messages to the CHANGELOG.
*For example:*
> Add community contribution thanks you

- CHANGELOG.md
- package.json
release fix for sourcemap vulnerability
> release 2.12.1

- CHANGELOG.md
- README.md
Adds a line specifying minimum supported typescript version to README, helps out with issue #601 .
N/A
> doc: add supported version for typescript

- CHANGELOG.md
- README.md
- index.js
- test/test.js
Added disallowedTagsMode: 'completelyDiscard' option to remove content from disallowed tags.
> added option disallowedTagsMode: 'completelyDiscard'

- CHANGELOG.md
- README.md
Adds a thanks for the community contribution to the CHANGELOG. Also fixes one sentence of the README.
*For example:*
> Fixes readme and adds thanks

- CHANGELOG.md
- package.json
> release 2.13.0

- CHANGELOG.md
- package.json
> release 2.14.0

- CHANGELOG.md
- package.json
> release 2.15.0

- CHANGELOG.md
- package.json
> release 2.16.0

- CHANGELOG.md
- package.json
> release 2.17.0
